# Copyright (c) The ThingSet Project Contributors
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject
      url-base: https://github.com/zephyrproject-rtos
    - name: thingset
      url-base: https://github.com/ThingSet
    - name: libresolar
      url-base: https://github.com/LibreSolar
    - name: garethpotter
      url-base: https://github.com/garethpotter
  projects:
    - name: zephyr
      remote: zephyrproject
      revision: v3.5-branch
      import:
        name-allowlist:
          - cmsis
          - edtt
          - hal_espressif
          - hal_nordic
          - hal_stm32
          - hal_st
          - loramac-node
          - mbedtls
          - tinycrypt
          - picolibc
    - name: thingset-node-c
      remote: garethpotter
      revision: 0e4c72346a125177c0ee8d0d3a42863d2f7ce1c1
      path: modules/thingset-node-c
      import: true
